mixing_coefficient: 1.
sigma1: 1.
sigma2: 2. # This won't be used since mixing coefficient is 1
n_samples: 10
n_samples_testing: 100
batch_size: 32
n_features:
out_features: 2
dataset_name: 
timestamp: 
classification: False
var_noise: 1.
learning_rate: 0.001

# Bayesian Layer parameters
bayesian_weight_rho_scale: -5.
bayesian_bias_rho_scale: -5.
bayesian_scale: 1.

